<?php

namespace AppBundle\Repository;

/**
 * OgloszeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OgloszeniaRepository extends \Doctrine\ORM\EntityRepository
{
}
